services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-5000}:5000'
    environment:
      DEV_MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    volumes:
      - .:/app
    env_file: .env
    restart: on-failure

  mongo:
    image: mongo:6
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - mongo-data:/data/db
    restart: on-failure
    healthcheck:
      test:
        mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 5

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo

volumes:
  mongo-data:
  data:
